### ISSUE TITLE
Contact Us today section

### ISSUE THREAD

**Issue by cocodrino** [tranduyhung/grav-skeleton-x-corporation#3]
Hi...I can't found what is the place where configure the links and text for the contact section in the home, I think than would be very handy for grav newbies if these themes and skeletons include an image indicating what is the respective section...

thank so much...

**Comment by tranduyhung** [comment]
I am not sure what contact section you mentioned is.

The images which are used in a page are stored in the page's folder. The content is in the MD file of the page. For example, you can find the info of the team members and their images here: https://github.com/tranduyhung/grav-skeleton-x-corporation/tree/master/pages/01.home/_team

**Comment by cocodrino** [comment]
![page](https://cloud.githubusercontent.com/assets/616412/19580839/ef373cf4-96f6-11e6-8f33-e99cab9fce53.png)

Hi...sorry if I did'n explain this well,I've uploaded a reference image... the section than I mean is the orange one with the the interrogation symbols inside...

I did a small example about the visual reference than I told you before...thank you so much

**Comment by tranduyhung** [comment]
Thank you for the info! The footer is used in all the pages so its data is stored in the theme's configuration: https://github.com/tranduyhung/grav-skeleton-x-corporation/blob/master/config/themes/x-corporation.yaml

It can also be stored in a page and retrieved by the theme. Grav is very flexible.

**Comment by cocodrino** [comment]
Hi..thank you for the info..this give me a better understand about how organize the code...I think than it's pretty clear, thank you
